real_names = {'am1': 'AM 1',
              'am4': 'AM 4',
              'booi': 'Bootes I',
              'booii': 'Bootes II',
              'carina': 'Carina',
              'comber': 'Coma Berenices',
              'cvni': 'Canes Venatici I',
              'cvnii': 'Canes Venatici II',
              'draco': 'Draco',
              'eri2': 'Eridanus II',
              'eri3': 'Eridanus III',
              'eridanus': 'Eridanus',
              'fornax': 'Fornax',
              'grus1': 'Grus I',
              'hercules': 'Hercules',
              'horo1': 'Horologium I',
              'horo2': 'Horologium II',
              'indus1': 'Indus I',
              'kop1': 'Koposov 1',
              'kop2': 'Koposov 2',
              'leoi': 'Leo I',
              'leoii': 'Leo II',
              'leoiv': 'Leo IV',
              'leot': 'Leo T',
              'leov': 'Leo V',
              'munoz1': 'Munoz 1',
              'ngc2419': 'NGC 2419',
              'ngc5694': 'NGC 5694',
              'ngc6229': 'NGC 6229',
              'ngc7006': 'NGC 7006',
              'ngc5824': 'NGC 5824',
              'ngc7492cfht': 'NGC 7492',
              'ngc7492clay': 'NGC 7492',
              'pal13': 'Palomar 13',
              'pal14': 'Palomar 14',
              'pal15': 'Palomar 15',
              'pal2': 'Palomar 2',
              'pal3clay': 'Palomar 3',
              'pal3cfht': 'Palomar 3',
              'pal4': 'Palomar 4',
              'pho2': 'Phoenix II',
              'pic1': 'Pictoris I',
              'pis2': 'Pisces II',
              'pyx': 'Pyxis',
              'ret2': 'Reticulum II',
              'scl': 'Sculptor',
              'segue1clay': 'Segue 1',
              'segue1cfht': 'Segue 1',
              'segue3': 'Segue 3',
              'segue2': 'Segue 2',
              'sextans': 'Sextans',
              'tuc2': 'Tucana II',
              'umai': 'Ursa Major I',
              'umaii': 'Ursa Major II',
              'umi': 'Ursa Minor',
              'whit1': 'Whiting 1',
              'wil1': 'Willman 1'
         }
